version: '3.8'

services:
  catering-app-dev:
    build:
      context: ..
      dockerfile: ./jdim2141-spring/Dockerfile
      args:
        profile: dev
    ports:
      - ${CATERING_APP_PORT}:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
