spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: true

auth.jwt:
  expiration: 86400000
  issuer: auth-service

springdoc:
  swagger-ui:
    operations-sorter: method


pagination:
  default:
    page: 0
    limit: 6

sorting:
  default:
    order: DESC
    sortBy: id
